
site_name: The Chronicle of Samogitia
site_description: A monumental chronicle of Samogitia — rulers, wars, faith, and the forest-born strength of a people.
site_url: https://YOUR_USERNAME.github.io/YOUR_REPO/
repo_url: https://github.com/YOUR_USERNAME/YOUR_REPO

theme:
  name: material
  logo: images/coat-of-arms.png
  favicon: images/coat-of-arms.png
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: brown
      accent: amber
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to night reading
extra_css:
  - stylesheets/epic.css
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/init.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Title Page: index.md
  - Prologue:
      - Origins: prologue/origins.md
      - Geography: prologue/geography.md
  - Chronicle of the Kings:
      - Duke Rolandas Drungilas: chronicle/01-first-ruler.md
      - The Second Ruler: chronicle/02-second-ruler.md
  - Culture & Society:
      - Religion: culture/religion.md
      - Military: culture/military.md
      - Economy: culture/economy.md
      - Society: culture/society.md
      - Arts: culture/arts.md
  - Appendices:
      - Roll of Kings: appendices/rulers-list.md
      - Timelines: appendices/timelines.md
      - Symbols & Arms: appendices/symbols.md
      - Maps: appendices/maps.md
